// src/game/invadersLevel.js
//
// Embedded prototype level used by SpaceInvadersMode. Mirrors the
// contents of levels/invaders.json so the mode works offline / without
// a fetch round-trip. The mode deep-clones this object per wave and
// scales spawner intervals + emit limits for difficulty progression.
//
// Key design choices baked into the prototype:
//   • Tiny friendly area (DRAW_ZONE_FRACTION=0.2) — cities sit near
//     the bottom and the player only has a narrow band to defend in.
//   • Aggressive enemy aging (MISSILE_AGE_ENEMY=6) so debris is
//     pruned before it accumulates into immortal junk.
//   • Wrap vertical shift of +10 cells creates a Klein-bottle-style
//     wrap that makes east/west escape paths drop diagonally.
//   • Only the "glider" pattern is allowed for the player — this
//     is the Space Invaders weapon of choice.
//   • Spawners use LWSS/MWSS/HWSS at the east edge to create
//     leftward-cruising invader formations, plus three "51p20h10v0"
//     oscillator spawners that emit periodically as motherships.
//
// The wave-scaling logic in SpaceInvadersMode.js modulates emitLimit,
// interval, and initialDelay; everything else (grid size, cities,
// settings, allowed patterns, wrap shift) is preserved exactly.

export const INVADERS_LEVEL = {
  name: 'SpaceInvaders',
  createdAt: 1780884837527,
  gridWidth: 300,
  gridHeight: 200,
  cities: [
    { x: 26, y: 161, width: 5, height: 3 },
    { x: 67, y: 161, width: 5, height: 3 },
    { x: 111, y: 161, width: 5, height: 3 },
    { x: 154, y: 161, width: 5, height: 3 },
    { x: 197, y: 161, width: 5, height: 3 },
    { x: 237, y: 161, width: 5, height: 3 },
    { x: 280, y: 161, width: 5, height: 3 },
  ],
  defenses: [],
  enemies: [],
  barriers: [],
  fire: [],
  bases: [],
  spawners: [
    {
      patternId: 'lwss',
      name: 'Lightweight Spaceship (LWSS)',
      x: 290,
      y: 81,
      width: 5,
      height: 4,
      cells: [
        [1, 0],
        [4, 0],
        [0, 1],
        [0, 2],
        [4, 2],
        [0, 3],
        [1, 3],
        [2, 3],
        [3, 3],
      ],
      interval: 2000,
      emitLimit: 10,
      initialDelay: 5000,
      padding: 4,
    },
    {
      patternId: 'lwss',
      name: 'Lightweight Spaceship (LWSS)',
      x: 290,
      y: 69,
      width: 5,
      height: 4,
      cells: [
        [1, 0],
        [4, 0],
        [0, 1],
        [0, 2],
        [4, 2],
        [0, 3],
        [1, 3],
        [2, 3],
        [3, 3],
      ],
      interval: 2000,
      emitLimit: 10,
      initialDelay: 5000,
      padding: 4,
    },
    {
      patternId: 'mwss',
      name: 'Middleweight Spaceship (MWSS)',
      x: 289,
      y: 56,
      width: 6,
      height: 5,
      cells: [
        [3, 0],
        [1, 1],
        [5, 1],
        [0, 2],
        [0, 3],
        [5, 3],
        [0, 4],
        [1, 4],
        [2, 4],
        [3, 4],
        [4, 4],
      ],
      interval: 2000,
      emitLimit: 10,
      initialDelay: 5000,
      padding: 4,
    },
    {
      patternId: 'mwss',
      name: 'Middleweight Spaceship (MWSS)',
      x: 289,
      y: 43,
      width: 6,
      height: 5,
      cells: [
        [3, 0],
        [1, 1],
        [5, 1],
        [0, 2],
        [0, 3],
        [5, 3],
        [0, 4],
        [1, 4],
        [2, 4],
        [3, 4],
        [4, 4],
      ],
      interval: 2000,
      emitLimit: 10,
      initialDelay: 5000,
      padding: 4,
    },
    {
      patternId: 'hwss',
      name: 'Heavyweight Spaceship (HWSS)',
      x: 288,
      y: 32,
      width: 7,
      height: 5,
      cells: [
        [3, 0],
        [4, 0],
        [1, 1],
        [6, 1],
        [0, 2],
        [0, 3],
        [6, 3],
        [0, 4],
        [1, 4],
        [2, 4],
        [3, 4],
        [4, 4],
        [5, 4],
      ],
      interval: 2000,
      emitLimit: 10,
      initialDelay: 5000,
      padding: 4,
    },
    {
      patternId: 'hwss',
      name: 'Heavyweight Spaceship (HWSS)',
      x: 288,
      y: 21,
      width: 7,
      height: 5,
      cells: [
        [3, 0],
        [4, 0],
        [1, 1],
        [6, 1],
        [0, 2],
        [0, 3],
        [6, 3],
        [0, 4],
        [1, 4],
        [2, 4],
        [3, 4],
        [4, 4],
        [5, 4],
      ],
      interval: 2000,
      emitLimit: 10,
      initialDelay: 5000,
      padding: 4,
    },
    {
      patternId: '51p20h10v0',
      name: '51p20h10v0',
      x: 274,
      y: 21,
      width: 10,
      height: 18,
      cells: [
        [6, 0],
        [7, 0],
        [4, 1],
        [9, 1],
        [3, 2],
        [3, 3],
        [9, 3],
        [3, 4],
        [4, 4],
        [5, 4],
        [6, 4],
        [7, 4],
        [8, 4],
        [1, 8],
        [2, 8],
        [0, 9],
        [1, 9],
        [3, 9],
        [4, 9],
        [5, 9],
        [6, 9],
        [7, 9],
        [8, 9],
        [9, 9],
        [1, 10],
        [2, 10],
        [3, 10],
        [4, 10],
        [5, 10],
        [6, 10],
        [7, 10],
        [8, 10],
        [2, 11],
        [3, 11],
        [4, 11],
        [5, 11],
        [6, 11],
        [7, 11],
        [6, 13],
        [7, 13],
        [4, 14],
        [9, 14],
        [3, 15],
        [3, 16],
        [9, 16],
        [3, 17],
        [4, 17],
        [5, 17],
        [6, 17],
        [7, 17],
        [8, 17],
      ],
      interval: 2000,
      emitLimit: 1,
      initialDelay: 20000,
      padding: 4,
    },
    {
      patternId: '51p20h10v0',
      name: '51p20h10v0',
      x: 274,
      y: 43,
      width: 10,
      height: 18,
      cells: [
        [6, 0],
        [7, 0],
        [4, 1],
        [9, 1],
        [3, 2],
        [3, 3],
        [9, 3],
        [3, 4],
        [4, 4],
        [5, 4],
        [6, 4],
        [7, 4],
        [8, 4],
        [1, 8],
        [2, 8],
        [0, 9],
        [1, 9],
        [3, 9],
        [4, 9],
        [5, 9],
        [6, 9],
        [7, 9],
        [8, 9],
        [9, 9],
        [1, 10],
        [2, 10],
        [3, 10],
        [4, 10],
        [5, 10],
        [6, 10],
        [7, 10],
        [8, 10],
        [2, 11],
        [3, 11],
        [4, 11],
        [5, 11],
        [6, 11],
        [7, 11],
        [6, 13],
        [7, 13],
        [4, 14],
        [9, 14],
        [3, 15],
        [3, 16],
        [9, 16],
        [3, 17],
        [4, 17],
        [5, 17],
        [6, 17],
        [7, 17],
        [8, 17],
      ],
      interval: 2000,
      emitLimit: 1,
      initialDelay: 20000,
      padding: 4,
    },
    {
      patternId: '51p20h10v0',
      name: '51p20h10v0',
      x: 274,
      y: 68,
      width: 10,
      height: 18,
      cells: [
        [6, 0],
        [7, 0],
        [4, 1],
        [9, 1],
        [3, 2],
        [3, 3],
        [9, 3],
        [3, 4],
        [4, 4],
        [5, 4],
        [6, 4],
        [7, 4],
        [8, 4],
        [1, 8],
        [2, 8],
        [0, 9],
        [1, 9],
        [3, 9],
        [4, 9],
        [5, 9],
        [6, 9],
        [7, 9],
        [8, 9],
        [9, 9],
        [1, 10],
        [2, 10],
        [3, 10],
        [4, 10],
        [5, 10],
        [6, 10],
        [7, 10],
        [8, 10],
        [2, 11],
        [3, 11],
        [4, 11],
        [5, 11],
        [6, 11],
        [7, 11],
        [6, 13],
        [7, 13],
        [4, 14],
        [9, 14],
        [3, 15],
        [3, 16],
        [9, 16],
        [3, 17],
        [4, 17],
        [5, 17],
        [6, 17],
        [7, 17],
        [8, 17],
      ],
      interval: 2000,
      emitLimit: 1,
      initialDelay: 20000,
      padding: 4,
    },
  ],
  ruleset: 'conway',
  enemyRuleset: null,
  description: 'Space Invaders prototype: spaceships cruise westward toward your cities.',
  settings: {
    INITIAL_INK: 80,
    MAX_INK: 140,
    INK_REGEN_RATE: 0.25,
    TICK_RATE: 100,
    STARTING_SPEED: 4,
    DEFENDER_TICKS: 1,
    ATTACKER_TICKS: 2,
    MISSILES_PER_WAVE_BASE: 8,
    MISSILES_PER_WAVE_INC: 3,
    MISSILE_SPAWN_INTERVAL: 800,
    MISSILE_SPAWN_DECREMENT: 75,
    MISSILE_SPAWN_MIN: 300,
    DEFENSE_AGE_FRIENDLY: 200,
    DEFENSE_AGE_ENEMY: 20,
    DEFENSE_AGE_NEUTRAL: 200,
    MISSILE_AGE_FRIENDLY: 32,
    MISSILE_AGE_ENEMY: 6,
    MISSILE_AGE_NEUTRAL: 6,
    AGE_CONTAGION_AMOUNT: 10,
    CLEAR_REFUND_FRACTION: 0.5,
    INK_DRY_TICKS: 5,
    DRAW_ZONE_FRACTION: 0.2,
    REAR_DEAD_ZONE_HEIGHT: 2,
    BASE_ZONE_HEIGHT: 102,
    BASE_SPAWN_COUNT_BASE: 1,
    BASE_SPAWN_COUNT_INC: 0.5,
    BASE_SPAWN_MAX: 6,
    BASE_GLIDER_BUFFER: 4,
    GLIDER_SE: true,
    GLIDER_SW: true,
    GLIDER_HEAVY: false,
    GLIDER_LWSS: false,
    GLIDER_MWSS: false,
    GLIDER_TWIN: false,
    GLIDER_GUN: false,
    HARDCORE_MODE: false,
    SHOW_DRAW_ZONE: true,
    BASE_SPAWN_ENABLED: true,
    ABILITY_DOUBLE_SCORE: true,
    ABILITY_NO_DRY: true,
    ABILITY_WAVE_BONUS: true,
    ABILITY_SAFE_ZONE: true,
    ABILITY_SLOW_MISSILES: true,
    ABILITY_EMP_BURST: true,
    ABILITY_INK_SURGE: true,
    ABILITY_FREEZE: true,
    SIM_HASHLIFE_ENABLED: true,
    VFX_PARTICLES: true,
    VFX_SHOCKWAVES: true,
    VFX_FLOATERS: true,
    VFX_SCREEN_SHAKE: true,
    VFX_CELL_GLOW: true,
    VFX_DRAW_ZONE_TINT: true,
    MISSILE_CASCADE_TICKS: 29,
    UNLIMITED_CELL_AGE: true,
    UNLIMITED_DEF_AGE_FRIENDLY: true,
    UNLIMITED_DEF_AGE_ENEMY: false,
    UNLIMITED_MISS_AGE_FRIENDLY: false,
    UNLIMITED_MISS_AGE_ENEMY: false,
    UNLIMITED_DEF_AGE_NEUTRAL: false,
    UNLIMITED_MISS_AGE_NEUTRAL: false,
  },
  allowedTools: {
    freehand: false,
    line: false,
    pattern: true,
    fill: false,
  },
  allowedPatterns: ['glider'],
  colorTheme: {},
  wrapVerticalShift: 10,
};
