#!/usr/bin/env node
  /**
   * Generates src/version.js with build metadata (git hash, build time, etc.).
   *
   * The generated file is intentionally tiny and is fetched at runtime with
   * `cache: 'no-store'` so the PWA can detect when a newer build has been
   * deployed and invalidate its service-worker cache accordingly.
   *
   * Run via:  npm run gen:version
   */
  import { execSync } from 'node:child_process';
  import { writeFileSync, readFileSync, existsSync } from 'node:fs';
  import { fileURLToPath } from 'node:url';
  import { dirname, resolve } from 'node:path';

  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const ROOT = resolve(__dirname, '..');
  const OUT_PATH = resolve(ROOT, 'src', 'version.js');

  function sh(cmd, fallback = 'unknown') {
    try {
      return execSync(cmd, { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] })
        .toString()
        .trim();
    } catch {
      return fallback;
    }
  }

  function readPkgVersion() {
    try {
      const pkgPath = resolve(ROOT, 'package.json');
      if (!existsSync(pkgPath)) return '0.0.0';
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
      return pkg.version || '0.0.0';
    } catch {
      return '0.0.0';
    }
  }

  const gitHash = sh('git rev-parse HEAD');
  const gitShortHash = sh('git rev-parse --short HEAD');
  const gitBranch = sh('git rev-parse --abbrev-ref HEAD');
  const gitDirty = sh('git status --porcelain') !== '' ? '-dirty' : '';
  const gitTag = sh('git describe --tags --abbrev=0', '');
  const buildTime = new Date().toISOString();
  const pkgVersion = readPkgVersion();

  const meta = {
    version: pkgVersion,
    gitHash,
    gitShortHash: gitShortHash + gitDirty,
    gitBranch,
    gitTag,
    dirty: gitDirty === '-dirty',
    buildTime,
    buildTimestamp: Date.now(),
  };

  const banner =
    '// AUTO-GENERATED by scripts/gen-version.js — do not edit by hand.\n' +
    '// Regenerate via: npm run gen:version\n' +
    `// Generated: ${buildTime}\n`;

  const body =
    `export const VERSION = ${JSON.stringify(meta, null, 2)};\n` +
    `export default VERSION;\n`;

  writeFileSync(OUT_PATH, banner + body, 'utf8');
  console.log(`[gen-version] wrote ${OUT_PATH}`);
  console.log(`  version: ${meta.version}`);
  console.log(`  git:     ${meta.gitShortHash} (${meta.gitBranch})`);
  console.log(`  built:   ${meta.buildTime}`);