// AUTO-GENERATED by scripts/gen-version.js — do not edit by hand.
// Regenerate via: npm run gen:version
// Generated: 2026-06-08T21:11:14.667Z
export const VERSION = {
  "version": "0.1.0",
  "gitHash": "748ba668a045c2f63c1045c390a6396040533b65",
  "gitShortHash": "748ba66",
  "gitBranch": "main",
  "gitTag": "0.0.1",
  "dirty": false,
  "buildTime": "2026-06-08T21:11:14.667Z",
  "buildTimestamp": 1780953074668
};
export default VERSION;
