// AUTO-GENERATED by scripts/gen-version.js — do not edit by hand.
// Regenerate via: npm run gen:version
// Generated: 2026-06-08T17:03:28.080Z
export const VERSION = {
  "version": "0.0.0",
  "gitHash": "8e490bbc7ec2947a933e728edbec490db5b3c273",
  "gitShortHash": "8e490bb",
  "gitBranch": "main",
  "gitTag": "",
  "dirty": false,
  "buildTime": "2026-06-08T17:03:28.080Z",
  "buildTimestamp": 1780938208080
};
export default VERSION;
